'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Art
    Public Property CreationDate() As Date?
    Public Property OwnerUserName() As String
    Public Property Type() As String
    Public Property LastWriteTime() As Date?
    Public Property Name() As String
    Public Property ID() As Integer
    Public Property ParentID() As Integer?
    Public Property IsFolder() As Boolean?
    Public Property Data() As Byte()
    Public Property OptimisticLockField() As Integer?
    Public Property GCRecord() As Integer?
    Public Property SSMA_TimeStamp() As Byte()
End Class
