//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Art
{
    public Nullable<System.DateTime> CreationDate { get; set; }
    public string OwnerUserName { get; set; }
    public string Type { get; set; }
    public Nullable<System.DateTime> LastWriteTime { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public Nullable<int> ParentID { get; set; }
    public Nullable<bool> IsFolder { get; set; }
    public byte[] Data { get; set; }
    public Nullable<int> OptimisticLockField { get; set; }
    public Nullable<int> GCRecord { get; set; }
    public byte[] SSMA_TimeStamp { get; set; }
}
